language: node_js
node_js:
    - 0.4
    - 0.6
branches:
    only:
        - travis
script:
    - ./src/common/travis/before.sh
install:
    - ./src/common/travis/install.sh
test:
    - ./src/common/travis/test.sh

