language: node_js
node_js:
    - 0.4
    - 0.6
    - 0.8
branches:
    only:
        - fix-node-gc
before_install:
    - ./src/common/travis/before.sh
install:
    - ./src/common/travis/install.sh
script:
    - ./src/common/travis/test.sh
